# Generated by Django 5.1.7 on 2025-03-26 11:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorName', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='default.png', upload_to='', verbose_name='演员头像')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=50)),
                ('videoDetails', django_ckeditor_5.fields.CKEditor5Field(verbose_name='影视详情')),
                ('cover', models.ImageField(default='default.png', upload_to='', verbose_name='封面')),
                ('actor', models.ManyToManyField(related_name='video', to='video.actor')),
                ('category', models.ManyToManyField(related_name='video', to='video.category')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='video.video')),
            ],
        ),
    ]
