# Generated by Django 5.1.7 on 2025-03-24 12:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=50)),
                ('videoDetails', django_ckeditor_5.fields.CKEditor5Field(verbose_name='影视详情')),
                ('cover', models.ImageField(default='default.png', upload_to='', verbose_name='封面')),
                ('actor', models.ManyToManyField(related_name='video', to='video.actor')),
            ],
        ),
    ]
