# Generated by Django 5.1.7 on 2025-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='ActorName',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='video', to='video.category'),
        ),
    ]
