# Generated by Django 5.1.7 on 2025-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_category_rename_name_actor_actorname_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='演员头像'),
        ),
    ]
